spring.application.name=gymApp
server.port=8080

# ===== PostgreSQL Render =====
spring.datasource.url=jdbc:postgresql://dpg-dapf2tjm8hqs739j32tg-a.oregon-postgres.render.com:5432/gym_083s?sslmode=require
spring.datasource.username=gym_083s_user
spring.datasource.password=0uNGxFTkAhZD7q50dRuHFYk85bTtkKBg
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===== RENIEC API =====
reniec.api.url=https://apiperu.dev/api/dni
reniec.api.token=sk_14673.GXVomSSEMgzK8zm1mOj3SdHgc49q7E6K